defdict = {'手紙': 'てがみ letter', '歌手': 'かしゅ singer', '手話': 'しゅわ sign language', '上手な': 'じょうずな good at',
           '紙': 'かみ paper', '和紙': 'わし Japanese paper', '表紙': 'ひょうし front cover', '折り紙': 'おりがみ origami',
           '好きな': 'すきな to like', '好意': 'こうい good will, favor', '好み': 'このみ liking, taste, choice',
           '好物': 'こうぶつ favorite food', '近く': 'ちかく nearby, near, close', '近所': 'きんじょ neighborhood',
           '最近': 'さいきん recently, lately', '中近東': 'ちゅうきんとう the Middle and Near East', '明るい': 'あかるい bright',
           '説明': 'せつめい explanation', '発明': 'はつめい invention', '文明': 'ぶんめい civilization', '病院': 'びょういん hospital',
           '病気': 'びょうき illness', '重病': 'じゅうびょう serious illness', '急病': 'きゅうびょう sudden illness',
           '大学院': 'だいがくいん graduate school', '美容院': 'びよういん beauty parlor', '映画': 'えいが movie',
           '映画館': 'えいがかん movie theater', '映る': 'うつる to be reflected', '画家': 'がか painter',
           '計画': 'けいかく plan', '漫画': 'まんが manga, comic', '歌': 'うた song', '国歌': 'こっか national anthem',
           '歌舞伎': 'かぶき Kabuki', '歌詞': 'かし lyrics', '川口市': 'かわぐちし Kawaguchi City',
           '市役所': 'しやくしょ city hall', '市長': 'しちょう mayor', '市場': 'いちば market', '台所': 'だいどころ kitchen',
           '住所': 'じゅうしょ address', '勉強する': 'べんきょうする to study', '勉める': 'つとめる to try hard',
           '勤勉な': 'きんべんな diligent', '強い': 'つよい strong', '強情な': 'ごうじょうな obstinate, stubborn',
           '強盗': 'ごうとう robbery', '強力な': 'きょうりょくな powerful', '有名な': 'ゆうめいな famous',
           '有料': 'ゆうりょう toll, fee', '有る': 'ある to exist', '有能な': 'ゆうのうな talented', '旅行': 'りょこう travel',
           '旅館': 'りょかん Japanese inn', '一人旅': 'ひとりたび traveling alone', '旅券': 'りょけん passport',
           '手': 'て/しゅ hand', '好': 'す/こう/この to like', '近': 'ちか/きん near', '明': 'あか/めい bright',
           '病': 'びょう ill', '院': 'いん institution', '映': 'えい/うつ to reflect', '画': 'が/かく picture',
           '市': 'し/いち city', '所': 'ところ/どろこ/しょ/じょ place', '勉': 'べん/つと to make efforts',
           '強': 'つよ/きょう/ごう strong', '有': 'ゆう/あ to exist', '旅': 'りょ/たび travel'}
